nelmio_cors:
    defaults:
        origin_regex: false
        allow_origin: []
        allow_methods: []
        allow_headers: []
        expose_headers: []
        max_age: 3600
    paths:
        '^/api': 
            allow_origin: ['http://localhost:3000']
            allow_headers: ['*']
            allow_methods: ['POST', 'OPTIONS', 'PUT', 'GET', 'DELETE']
            max_age: 3600